name: react-workflow
on: push  #for multiple triggers use lists example [push, etc]
jobs:
   first:
      runs-on: ubuntu-latest
      steps:
      -  name: get code
         uses: actions/checkout@v4
      -  name: install nodejs
         uses: actions/setup-node@v4
         with: 
            node-version: 18
      -  name: install dependencies
         run: |
            cd react && npm ci
      -  name: tests
         run: |
            cd react && npm test
   second:
      needs: first  # used for sequential running (in this second will run after succesfull running 
      # of first) and for multiple [first, etc] can be used
      runs-on: ubuntu-latest
      steps:
      -  name: get code
         uses: actions/checkout@v4
      -  name: install nodejs
         uses: actions/setup-node@v4
         with: 
            node-version: 18
      -  name: install dependencies
         run: |
            cd react && npm ci
      -  name: build
         run: |
            cd react && npm run build
